### PR TITLE
More robust fix for missing subtitles

### PR DESCRIPTION
**Pull request by mwhirls**
Instead of looking for hard coded property names in the Netflix requests, recursively search through the request properties to find the subtitle formats list.

### CODE REVIEW

**Comment by vitorsenna** [comment]
The subtitles was not showing before, they are like this now:
firefox_2020-04-26_16-22-30

But with this solution I can't copy them or use another extension that I have (img below) because the target language still not showing in the list.

firefox_2020-04-22_11-47-01

😔 sad

**Comment by mwhirls** [comment]
@vitorsenna I think that may be related to this issue (#20) and fixed here: https://github.com/rsimmons/subadub/pull/21

I think @Essam311 made a custom build that contains both fixes, as described here, that you can try:
https://github.com/rsimmons/subadub/issues/20#issuecomment-612777747

**Comment by vitorsenna** [comment]
Thank you @mwhirls I will try 😀

**Comment by rsimmons** [comment]
Thank you for this PR, and sorry that it took forever to merge. I've submitted updated builds for Chrome and Firefox.

**Pull request merged**
